services:
    api:
        build:
            context: .
            dockerfile: TestnaNalogaOresnik/Dockerfile
        ports:
            - "5000:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks:
            - app-network

networks:
    app-network:
        driver: bridge